      - name: Deploy & setup Mautic on VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ env.IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www
            echo "✅ Skipping domain IP check for CI/CD deployment"

            # Docker Compose build and up
            docker-compose build
            docker-compose up -d db mautic_web

            DB=$(docker-compose ps -q db)
            WEB=$(docker-compose ps -q mautic_web)

            echo "⏳ Waiting for containers to be ready..."
            docker exec $DB pg_isready -U postgres
            sleep 5  # short wait after DB ready
            docker exec $WEB sh -c 'echo Running'
            sleep 2  # short wait after web ready

            # Mautic install with retries
            for i in {1..5}; do
              echo "Attempt $i to install Mautic..."
              if docker-compose exec -T -u www-data -w /var/www/html $WEB php ./bin/console mautic:install --force --admin_email $EMAIL_ADDRESS --admin_password $MAUTIC_PASSWORD http://$IP:$MAUTIC_PORT; then
                echo "✅ Mautic installed successfully!"
                break
              else
                echo "Install failed, retrying in 10s..."
                sleep 10
              fi
            done

            docker-compose up -d

            # Nginx & HTTPS setup
            ln -sf /var/www/nginx-virtual-host-$DOMAIN /etc/nginx/sites-enabled/
            nginx -t && (systemctl start nginx || nginx -s reload)
            certbot --nginx -d $DOMAIN --non-interactive --agree-tos -m $EMAIL_ADDRESS
            (crontab -l 2>/dev/null; echo "0 0 1 * * certbot renew --post-hook 'systemctl reload nginx'") | crontab -

            # Update site_url
            echo "⏳ Waiting for Mautic to respond..."
            until curl -ks https://$DOMAIN | grep -q "Mautic"; do sleep 5; done

            docker-compose exec -T $WEB sed -i "s|'site_url' => '.*',|'site_url' => 'https://$DOMAIN',|g" /var/www/html/config/local.php
            echo "✅ Deployment complete!"
